@SmokeTest
Feature: Smoke Test

  Background: User is Logged In
    Given User redirects to "ta.staging"
    And "LOGIN_PAGE" shows up
    When User enter valid credentials
    Then "MASTER_PAGE" shows up


#  @SmokeTest-01
#  Scenario Outline: Smoke test by URL
#    Given User goes to "<tested_url>"
#    And Target page should be loaded completely
#    And Validate all URLs on page
#    When User verify "<tested_url_levels>"
#
#    Examples:
#      | tested_url                                                                    | tested_url_levels                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
#      | /home                                                                         | /employees - /employees/new - /employees/lNKkjtVsD-XGXi4MBin9Cw/edit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
#      | /tax_adjustments                                                              | /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/general_settings/basic_settings/edit - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/general_settings/declaration_guidelines - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/general_settings/tax_adjustment_notification_setting/edit - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/general_settings/logs - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/general_settings/tax_adjustment_alerts - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/imports/employee_information_csv - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/imports/payroll_information_csv - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/imports/employee_my_number - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/imports/insurance_information_csv - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/imports/housing_loan_csv - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/imports/employee_calculation_csv - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/imports/other_calculation - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/exports/basic_deduction_pdf - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/exports/dependent_deduction_pdf - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/exports/dependent_deduction_pdf?for_next_term=true - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/exports/insurance_deduction_pdf - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/exports/withholding_slip_pdf - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/exports/withholding_book_pdf - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/exports/payment_report_total_table_pdf - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/not_requested?search_tax_adjustment_employees_form%5Bprevious_status%5D=all - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/requested?search_tax_adjustment_employees_form%5Bprevious_status%5D=finalized - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/submitted?search_tax_adjustment_employees_form%5Bprevious_status%5D=requested - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/checked?search_tax_adjustment_employees_form%5Bprevious_status%5D=submitted - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/finalized?search_tax_adjustment_employees_form%5Bprevious_status%5D=checked - /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees_my_number - /tax_adjustments/Fa1bRTuPJBRtppp_NyatoA/tax_adjustment_employees/pdf_target - /tax_adjustments/Fa1bRTuPJBRtppp_NyatoA/withholding_slip_total/edit - /tax_adjustments/Fa1bRTuPJBRtppp_NyatoA/payment_report_total_tables - /tax_adjustments/Fa1bRTuPJBRtppp_NyatoA/payment_report_total_tables/L4XQhWaN8jaBkxg0sOT_Eg?tax_adjustment=Fa1bRTuPJBRtppp_NyatoA - /tax_adjustments/Fa1bRTuPJBRtppp_NyatoA/municipality_identification_codes - /tax_adjustments/Fa1bRTuPJBRtppp_NyatoA/prepare_electronic_filing - /tax_adjustments/Fa1bRTuPJBRtppp_NyatoA/send_electronic_filing |
#      | /office_submitters                                                            | /office_submitters/new - /office_submitters/T2JhK0h3XoauiFkzPkzaSg/edit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
#      | /offices/6h6lrOAwq3_UKGkg8BpMgw/groups                                        | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#      | /departments                                                                  | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#      | /electronic_filing_settings                                                   | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#      | /office_members                                                               | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#      | /attorneys/new                                                                | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#      | /attorneys/KfE1VaXsItC--szWgu7wgw/edit                                        | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#      | /connect_pages                                                                | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#      | /office_billings                                                              | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/general_settings/tax_adjustment_alerts| n/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
#
#
#  @SmokeTest-02
#  Scenario Outline: Smoke test by UI filtering
#    Given User navigate to "<func_name>" on left menu
#      And "<page_name>" shows up
#      And User open "<sub_page_url>" and verify "<sub_page_name>" if applicable
#    When User verify filter for "<func_name>" based on "<filter_data>"
#
#    Examples:
#      | func_name      | page_name           | sub_page_url                                                                   | sub_page_name     | filter_data                                                                                                                                                                                                                                               |
#      | Employee       | EMPLOYEE_PAGE       | n/a                                                                            |                   | 氏名（従業員番号） - tau001; 事業所 - Office Group; メールアドレス - auto001@tax.auto.com; 権限 - 一般従業員; 在籍状況 - 退職予定; 入社日 - 2021/10/25 ~ 2021/10/28; 退職日 - 2023/01/01 ~ 2023/01/31; 連携 - 連携なし                                                   |
#      | Authority      | AUTHORITY_PAGE      | n/a                                                                            |                   | 氏名（従業員番号） - tau001; メールアドレス - auto001@tax.auto.com; 権限名 - 一般従業員                                                                                                                                                                           |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | n/a                                                                            |                   | 年度を選択 - 2021年                                                                                                                                                                                                                                         |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | n/a                                                                            |                   | 年度を選択 - 2022年                                                                                                                                                                                                                                         |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/              | TA_EMPLOYEES_PAGE | 氏名（従業員番号） - tau001; 事業所 - Office Group; 契約種別 - 使用人兼務役員; 税額区分 - 甲; メールアドレス - 登録あり; アラート - 有; コメント - なし; 年末調整対象外理由 - 年収が2,000万円以上; 回収・計算ステータス - 確定済                                                    |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/not_requested | TA_EMPLOYEES_PAGE | 氏名（従業員番号） - tau002; 事業所 - Office Group; 契約種別 - 正社員; 入社日 - 2021/10/26; 退職日 - 2021/10/26; 税額区分 - 甲; メールアドレス - 登録あり; コメント - なし                                                                                               |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/requested     | TA_EMPLOYEES_PAGE | 氏名（従業員番号） - tau004; 事業所 - Office Group; 契約種別 - 正社員; 入社日 - 2021/10/28; 税額区分 - 甲; ログイン状況 - 無; 差戻しの有無 - 無; アラート - 無; コメント - なし                                                                                            |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/submitted     | TA_EMPLOYEES_PAGE | 氏名（従業員番号） - tau003; 事業所 - Office Group; 契約種別 - 正社員; 在籍状況 - 在籍中; 税区分 - 甲; 原本回収 - 未回収; 差戻しの有無 - 無; 申告書/配偶者 - 無; 申告書/扶養親族 - 無; 申告書/保険料控除 - 無; 申告書/住宅ローン - 無; 申告書/前職 - 無; アラート - 無; コメント - なし; |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/checked       | TA_EMPLOYEES_PAGE | 氏名（従業員番号） - tau005; 事業所 - Office Group; 契約種別 - 正社員; 在籍状況 - 在籍中; 入社日 - 2023/01/29; 税額区分 - 甲; アラート - 有; コメント - なし; 年末調整対象外理由 - 年収が2,000万円以上                                                                        |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | /tax_adjustments/qgAjo93DAlagQ-P8InGnCg/tax_adjustment_employees/finalized     | TA_EMPLOYEES_PAGE | 氏名（従業員番号） - tau001; 事業所 - Office Group; 契約種別 - 使用人兼務役員; 入社日 - 2021/10/25; 税額区分 - 甲; 原本回収 - 未回収; 源泉徴収票配布状況 - 未配布; アラート - 有; コメント - なし; 年末調整対象外理由 - 年収が2,000万円以上                                        |
#      | Tax Adjustment | TAX_ADJUSTMENT_PAGE | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/general_settings/tax_adjustment_alerts | TA_EMPLOYEES_PAGE | 氏名（従業員番号） - tau006; 契約種別 - 正社員; アラート/種別 - 注意; アラート/箇所 - 従業員情報; アラート/日付 - 2023/04/10; エラー/ステータス - 未読                                                                                                                 |


  @SmokeTest-03
  Scenario Outline: Smoke test by Submission
    Given User goes to "<tested_url>"
      And "<page_name>" shows up
    When User verify "<tested_func>" on "<page_name>"

    Examples:
      | tested_url                                                       | page_name | tested_func                              |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | General setting - Basic setting          |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | General setting - Declaration Guidelines |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | General setting - Notification           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | General setting - Alert                  |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Import - Employee information           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Import - Payroll information           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Import - My number                   |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Import - Insurance information           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Import - Housing loan           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Import - Previous withholding slip           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Import - Employee calculation           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Import - Other calculation           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Export - Basic Deduction           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Export - Dependent Deduction           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Export - Dependent Deduction For Next Term          |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Export - Insurance Deduction           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Export - Withholding Book           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Export - Withholding Slip           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Export - Payment Report Total Table           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Employee Detail - Declaration Form           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Employee Detail - Withholding Book           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Employee Detail - Withholding Slip           |
#      | /tax_adjustments/2Mvjaufm0cV6tCctvu1Q5g/tax_adjustment_employees | YETA_PAGE | Employee Detail - Payroll Payment report     |
#      | /tax_adjustments/9wEqbqsjm04zTxDSinBJRQ/tax_adjustment_employees | YETA_PAGE | Employee Detail - Calculation                |
      | /tax_adjustments/9wEqbqsjm04zTxDSinBJRQ/tax_adjustment_employees | YETA_PAGE | My Number                                 |










